final String friday = """[
{"Week":"1","Exercise":"Childs pose","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Lizard","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Pigeon","Time":"2","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Supine Twist","Time":"1.5","L/R?":"LR","SuperSet #":""},
{"Week":"2","Exercise":"Single leg forward fold","Time":"5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Lizard","Time":"4.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Sumo Eagle","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"3","Exercise":"Child's pose","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"happy baby","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Forward Fold","Time":"6","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"6","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Supine Twist","Time":"1","L/R?":"LR","SuperSet #":""},
{"Week":"4","Exercise":"Liard","Time":"1.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Twisted Lizard","Time":"1.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Half Saddle","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Puppy Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Supine Split","Time":"1.5","L/R?":"LR","SuperSet #":""},
{"Week":"5","Exercise":"Lizard","Time":"3.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Thread the Flat Needle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"6","Exercise":"Seated Forward Fold","Time":"4","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Supine Twist","Time":"1","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"4.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Dragon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"7","Exercise":"Standing Straddle","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Standing Forward Fold w/ Interlace Fingers","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Sumo Eagle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Thread the needle","Time":"1.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Twisted Cross","Time":"3","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Star","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"8","Exercise":"Saddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle Archer","Time":"1.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"9","Exercise":"Extended Arm Lizard","Time":"2","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Lizard","Time":"3","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Saddle","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"10","Exercise":"Thread the flat needle","Time":"1","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle Eagle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle Archer","Time":"1","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seated Forward Fold","Time":"4","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Fragon","Time":"1.5","L/R?":"LR","SuperSet #":""},
{"Week":"11","Exercise":"Single leg forward fold","Time":"1.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Half Seated Frog","Time":"2.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Lizard","Time":"2.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"12","Exercise":"Saddle","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"4","L/R?":"","SuperSet #":""},
{"Week":"13","Exercise":"Frog","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Cross shin eagle","Time":"4.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Supine twist","Time":"1","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Happy Baby","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"14","Exercise":"Twisted Cross","Time":"1.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Thread the needle","Time":"1.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Half Saddle","Time":"3.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"1","L/R?":"","SuperSet #":""}
]""";