final String monday = """[
{"Week":"1","Exercise":"Low dragon","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Pigeon","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Supine lizard","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Supine Twist","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"2","Exercise":"Twisted cross","Time":"2","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seated Stress","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"3","Exercise":"Dragon","Time":"1","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Half Split","Time":"1","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Fragon","Time":"2","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Lizard","Time":"2","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Puppy Dog","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"4","Exercise":"Saddle","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Lizard","Time":"1.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Dragon","Time":"3.5","L/R?":"LR","SuperSet #":""},
{"Week":"5","Exercise":"Half Saddle","Time":"7","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Forward Fold","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"4","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Single Leg Forward Fold","Time":"3","L/R?":"LR","SuperSet #":""},
{"Week":"6","Exercise":"Down Dog","Time":"2","L/R?":"","SuperSet #":"1"},
{"Week":"","Exercise":"Dragon","Time":"2","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Down Dog","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"7","Exercise":"Extended Arm Lizard","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Lizard","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Saddle Archer","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Twisted cross","Time":"1","L/R?":"LR","SuperSet #":""},
{"Week":"8","Exercise":"Bound Angle","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Thread the needle","Time":"1.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"5","L/R?":"","SuperSet #":""},
{"Week":"9","Exercise":"Extended Arm Lizard","Time":"2.75","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Lizard","Time":"1.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Twisted Lizard","Time":"1","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Down Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Standing Forward Fold w/ interlace fingers","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Sumo Eagle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"10","Exercise":"Half Saddle","Time":"4","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Low Dragon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"11","Exercise":"Standing Straddle","Time":"4","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Bound Angle","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle Archer","Time":"1.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Sumo Eagle","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Supine Twist","Time":"1.5","L/R?":"LR","SuperSet #":""},
{"Week":"12","Exercise":"Child's pose w/ shoulders","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Lizard","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Half Front Split","Time":"1","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Pigeon","Time":"3.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Puppy Dog","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"13","Exercise":"Single Leg Forward Fold","Time":"3","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Cross Shin","Time":"4","L/R?":"","SuperSet #":"1"},
{"Week":"","Exercise":"Seal","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"14","Exercise":"Extended Arm Lizard","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Pigeon","Time":"3.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Puppy Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Twisted Cross","Time":"1","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"START DEC 25","Exercise":"","Time":"","L/R?":"","SuperSet #":""}
]""";
