final String saturday = """[
{"Week":"1","Exercise":"Single leg forward fold","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Bound angle","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"7","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Half Saddle","Time":"5","L/R?":"","SuperSet #":""},
{"Week":"2","Exercise":"Dragon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Saddle Archer","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Twisted Cross","Time":"3.5","L/R?":"LR","SuperSet #":""},
{"Week":"3","Exercise":"Extended Arm Lizard","Time":"1","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Lizard","Time":"3","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Pigeon","Time":"3","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Twisted Cross","Time":"1.5","L/R?":"LR","SuperSet #":""},
{"Week":"4","Exercise":"Thread the needle","Time":"1.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Down Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Lizard","Time":"1","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Twisted Lizard","Time":"2","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Frog","Time":"4","L/R?":"","SuperSet #":""},
{"Week":"5","Exercise":"Figure 4 pigeon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Double Knee Twist","Time":"2","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seated Forward Fold","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"6","Exercise":"Twisted Cross","Time":"1","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Thread the needle","Time":"1","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Half Saddle","Time":"3.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"7","Exercise":"Low Dragon","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Half Front Split","Time":"1.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Down Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Sumo Squat","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Down Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Dragon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"8","Exercise":"Down Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Lizard","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Pigeon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Standing Straddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"9","Exercise":"Half Saddle","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"4","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"10","Exercise":"Lizard","Time":"1.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Half front split","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Fragon","Time":"2","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Puppy Dog","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Sumo Squat","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"11","Exercise":"Standing Straddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Sumo Squat","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Bound angle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Sumo Eagle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Standing Straddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Pigeon","Time":"2","L/R?":"LR","SuperSet #":""},
{"Week":"12","Exercise":"Standing Straddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Down Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Cross shin","Time":"6","L/R?":"","SuperSet #":""},
{"Week":"13","Exercise":"Half Front Split","Time":"1","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Low Dragon","Time":"3.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Saddle Archer","Time":"1.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Saddle Eagle","Time":"1","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"14","Exercise":"Standing Straddle","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Sumo Squat","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Pigeon","Time":"3.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"2.5","L/R?":"","SuperSet #":""}
]""";