final String sunday = """[
{"Week":"1","Exercise":"Bound Angle","Time":"5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Happy baby","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Dragon","Time":"5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"2","Exercise":"Low Dragon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Wrist Stretch","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Toe saddle","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle archer","Time":"4.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Low Dragon","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Pigeon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"3","Exercise":"Puppy Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Twisted Cross","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Single Leg forward fold","Time":"4","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Pigeon","Time":"4.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"4","Exercise":"Saddle Archer","Time":"1.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Fragon","Time":"1.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Lizard","Time":"1","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Half Front Split","Time":"1.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Pigeon","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"5","Exercise":"Dragon","Time":"3","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Cross Shin Eagle","Time":"1.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Cross Shin","Time":"1","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Double Pigeon","Time":"5.5","L/R?":"","SuperSet #":""},
{"Week":"6","Exercise":"Standing Straddle","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Sumo Squat","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Pigeon","Time":"3","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"7","Exercise":"Puppy Dog","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Twisted Cross","Time":"1.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Thread the Needle","Time":"1.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Saddle Eagle","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"4.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Bound Angle","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"8","Exercise":"Twisted Cross","Time":"1.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Half Saddle","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Low Dragon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Standing Straddle","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"9","Exercise":"Wrist Stretch","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle Eagle","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle archer","Time":"2","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Down Dog","Time":"0.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Low Dragon","Time":"1.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seated Forward fold","Time":"4.5","L/R?":"","SuperSet #":""},
{"Week":"10","Exercise":"Standing Straddle","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Lizard","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Half Front Split","Time":"1.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Fragon","Time":"2","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Standing Straddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"11","Exercise":"Dragon","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Half Front Split","Time":"1.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Fragon","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Lizard","Time":"1.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Saddle Archer","Time":"1.25","L/R?":"LR","SuperSet #":""},
{"Week":"12","Exercise":"Single Leg forward fold","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Pigeon","Time":"2","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Single Leg forward fold","Time":"1","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Supine Twist","Time":"1.5","L/R?":"LR","SuperSet #":""},
{"Week":"13","Exercise":"Figure 4 Pigeon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Double Knee twist","Time":"2.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seated Forward fold","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"14","Exercise":"Puppy Dog","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Single leg forward fold","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seated Cross shin","Time":"6.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"1.5","L/R?":"","SuperSet #":""}
]""";