final String thursday = """[
{"Week":"1","Exercise":"Child pose w/ shoulders","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Down dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Half Saddle","Time":"4","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Single leg forward fold","Time":"3","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Pigeon","Time":"3","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Forward Fold","Time":"10","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Supine Twist","Time":"2","L/R?":"LR","SuperSet #":""},
{"Week":"2","Exercise":"Twisted Cross","Time":"3","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Thread the needle","Time":"2","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Lizard","Time":"2","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Twisted Lizard","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Half Saddle","Time":"4.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Single leg forward fold","Time":"4.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Seated cross shin","Time":"5.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"3","Exercise":"Saddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Puppy dog","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Dragon","Time":"5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Lizard","Time":"4","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Fragon","Time":"7","L/R?":"LR","SuperSet #":""},
{"Week":"4","Exercise":"Standing Forward Fold w/ interlaced fingers","Time":"0.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Standing Straddle","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Standing Forward Fold w/ interlaced fingers","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Down Dog","Time":"1","L/R?":"","SuperSet #":"1"},
{"Week":"","Exercise":"Fragon","Time":"5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Lizard","Time":"3","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Half Front split","Time":"1","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Dragon","Time":"5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Pigeon","Time":"6","L/R?":"LR","SuperSet #":"1"},
{"Week":"5","Exercise":"Bound Angle","Time":"5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Single leg forward fold","Time":"3.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Half Saddle","Time":"3","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Pigeon","Time":"6","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Seated Straddle","Time":"4.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"6","L/R?":"","SuperSet #":""},
{"Week":"6","Exercise":"Standing Straddle","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Single leg forward fold","Time":"3.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Cross Shin","Time":"4","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Saddle","Time":"6","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Thread the needle","Time":"4","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Down Dog","Time":"0.5","L/R?":"","SuperSet #":"2"},
{"Week":"","Exercise":"Dragon","Time":"1","L/R?":"","SuperSet #":"2"},
{"Week":"","Exercise":"Lizard","Time":"1","L/R?":"","SuperSet #":"2"},
{"Week":"","Exercise":"Twisted Lizard","Time":"1","L/R?":"","SuperSet #":"2"},
{"Week":"7","Exercise":"Cross Shin","Time":"9","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"9","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle Eagle","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Pigeon","Time":"4.5","L/R?":"LR","SuperSet #":""},
{"Week":"8","Exercise":"Saddle","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Forward Fold","Time":"3.5","L/R?":"","SuperSet #":"1"},
{"Week":"","Exercise":"Extended Arm Lizard","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Lizard","Time":"2","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Twisted Lizard","Time":"2","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Frog","Time":"3.5","L/R?":"","SuperSet #":"1"},
{"Week":"","Exercise":"Seated Straddle","Time":"5.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"4","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Supine Twist","Time":"3.5","L/R?":"LR","SuperSet #":""},
{"Week":"9","Exercise":"Child's pose w/ shoulders","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Child's pose","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Tight double pigeon","Time":"3.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seated Forward Fold","Time":"4","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Half seated Frog","Time":"5.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Sumo squat","Time":"4","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Pigeon","Time":"4","L/R?":"LR","SuperSet #":""},
{"Week":"10","Exercise":"Saddle Archer","Time":"1.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Twisted Cross","Time":"1.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Saddle Archer","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Down Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Bound Angle","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"7","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Pigeon","Time":"5.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Dragon Archer","Time":"1.5","L/R?":"LR","SuperSet #":"2"},
{"Week":"","Exercise":"Dragon","Time":"2","L/R?":"LR","SuperSet #":"2"},
{"Week":"11","Exercise":"Saddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Dragon","Time":"1.5","L/R?":"","SuperSet #":"1"},
{"Week":"","Exercise":"Lizard","Time":"1.5","L/R?":"","SuperSet #":"1"},
{"Week":"","Exercise":"Puppy dog","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"5.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Dragon","Time":"1.5","L/R?":"LR","SuperSet #":"2"},
{"Week":"","Exercise":"Lizard","Time":"1","L/R?":"","SuperSet #":"2"},
{"Week":"","Exercise":"Puppy Dog","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"5.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Half seated Frog","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"12","Exercise":"Childs Pose w/ shoulders","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Dragon","Time":"4","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Half Split","Time":"1","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Low Dragon","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Twisted Cross","Time":"4","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Lizard","Time":"1.5","L/R?":"LR","SuperSet #":"2"},
{"Week":"","Exercise":"Pigeon","Time":"3","L/R?":"LR","SuperSet #":"2"},
{"Week":"","Exercise":"Double Pigeon","Time":"7","L/R?":"","SuperSet #":""},
{"Week":"13","Exercise":"Toe Saddle","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle Archer","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Single leg forward fold","Time":"4","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Half Saddle","Time":"5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Low Dragon","Time":"3.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Half Split + grab toe","Time":"3","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Sumo squat","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Sumo Squat w/ feet together","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Toe Saddle w/ extended leg","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"14","Exercise":"Saddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Puppy dog","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Dragon","Time":"4","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Lizard","Time":"4.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Fragon","Time":"7","L/R?":"LR","SuperSet #":""}
]""";