final String tuesday = """[
{"Week":"1","Exercise":"Saddle","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"4","L/R?":"","SuperSet #":""},
{"Week":"2","Exercise":"Half saddle","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seated forward fold","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Half seated Frog","Time":"2","L/R?":"","SuperSet #":"1"},
{"Week":"","Exercise":"Cross Shin","Time":"2","L/R?":"","SuperSet #":"2"},
{"Week":"3","Exercise":"Down Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Twisted Cross","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Thread the needle","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Lizard","Time":"2","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"4","Exercise":"Single Leg Forward Fold","Time":"1","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Childs Pose w/ shoulder","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"5","Exercise":"Puppy Dog","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Single Leg Forward Fold","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seated Cross Shin","Time":"3.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"6","Exercise":"Seated Cross Shin","Time":"5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"4","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Down Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"7","Exercise":"Bound Angle","Time":"4","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Single Leg Forward Fold","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Cross Shin Eagle","Time":"1","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Seated Cross Shin","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"8","Exercise":"Frog","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Child's pose w/ shoulders","Time":"1.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Lizard","Time":"3","L/R?":"LR","SuperSet #":""},
{"Week":"9","Exercise":"Saddle Eagle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Thread the flat needle","Time":"1.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"10","Exercise":"Dragon","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Half Front Split","Time":"1.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Fragon","Time":"2","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Lizard","Time":"2","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Sumo Eagle","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"11","Exercise":"Saddle Eagle","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Low Dragon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Pigeon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"12","Exercise":"Single Leg Forward Fold","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Pigeon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seated forward fold","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle Eagle","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"13","Exercise":"Dragon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Lizard","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Twisted Lizard","Time":"1.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"14","Exercise":"Saddle Eagle","Time":"1.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Saddle Archer","Time":"1.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"4.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"4.5","L/R?":"","SuperSet #":""}
]""";