final String wednesday = """[
{"Week":"1","Exercise":"Single leg forward fold","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Pigeon","Time":"2","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Single leg forward fold","Time":"1","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Supine twist","Time":"3","L/R?":"LR","SuperSet #":""},
{"Week":"2","Exercise":"Saddle","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Extended Arm Lizard","Time":"1.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Low Dragon","Time":"2","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Bound Angle","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Supine Twist","Time":"1","L/R?":"LR","SuperSet #":""},
{"Week":"3","Exercise":"Standing Straddle","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Down dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated cross shin","Time":"7","L/R?":"","SuperSet #":""},
{"Week":"4","Exercise":"Dragon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Seated Forward Fold","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Cross Shin","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"5","Exercise":"Frog","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Cross Shin eagle","Time":"4.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Supine Twist","Time":"1","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Happy Baby","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"6","Exercise":"Supine Twist","Time":"5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Happy Baby","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Supine Split","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Pigeon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"7","Exercise":"Saddle Archer","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Forward Fold","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Cross Shin","Time":"4.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"8","Exercise":"Saddle","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Frog","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seated Straddle","Time":"4","L/R?":"","SuperSet #":""},
{"Week":"9","Exercise":"Bound Angle","Time":"5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Happy Baby","Time":"0.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Dragon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"3","L/R?":"","SuperSet #":""},
{"Week":"10","Exercise":"Toe saddle","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Down dog","Time":"1","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Sumo Squat","Time":"2","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Pigeon","Time":"3","L/R?":"LR","SuperSet #":""},
{"Week":"11","Exercise":"Puppy Dog","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Seal","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Flat thread the needle","Time":"2.25","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Standing Straddle","Time":"3.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Sumo Squat","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"12","Exercise":"Half Saddle","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Saddle","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Down Dog","Time":"1.5","L/R?":"","SuperSet #":""},
{"Week":"","Exercise":"Twisted Cross","Time":"2","L/R?":"LR","SuperSet #":""},
{"Week":"13","Exercise":"Low Dragon","Time":"2.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Fragon","Time":"1.5","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Lizard","Time":"1","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Fragon","Time":"2","L/R?":"LR","SuperSet #":""},
{"Week":"","Exercise":"Puppy Dog","Time":"2.5","L/R?":"","SuperSet #":""},
{"Week":"14","Exercise":"Down Dog","Time":"1","L/R?":"","SuperSet #":"1"},
{"Week":"","Exercise":"Lizard","Time":"2.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Fragon","Time":"3.5","L/R?":"LR","SuperSet #":"1"},
{"Week":"","Exercise":"Saddle Eagle","Time":"1","L/R?":"LR","SuperSet #":""}
]""";